%YAML:1.0
image_width: 416
image_height: 416
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [294.11422, 0.0, 204.03416,
          0.0, 392.02531, 204.86845,
          0.0, 0.0, 1.0]

distortion_coefficients: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [0.012725, -0.014285, 0.001474, -0.000467, 0.0]

rectification_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [1.0, 0.0, 0.0,
          0.0, 1.0, 0.0,
          0.0, 0.0, 1.0]

projection_matrix: !!opencv-matrix
   rows: 3
   cols: 4
   dt: d
   data: [295.11769, 0.0, 203.80028, 0.0,
          0.0, 393.35348, 205.46615, 0.0,
          0.0, 0.0, 1.0, 0.0]

